#ifndef __DATA_TYPES_H
#define __DATA_TYPES_H


/*
	GPIO defines for device
*/
#define DISPLAY_LED_I				GPIO_Pin_6
#define DISPLAY_LED_I_ON		GPIO_SetBits(GPIOA, DISPLAY_LED_I)
#define DISPLAY_LED_I_OFF		GPIO_ResetBits(GPIOA, DISPLAY_LED_I)

#define	DISPLAY_LED_II			GPIO_Pin_7
#define DISPLAY_LED_II_ON		GPIO_SetBits(GPIOA, DISPLAY_LED_II)
#define DISPLAY_LED_II_OFF	GPIO_ResetBits(GPIOA, DISPLAY_LED_II)

#define PULSE_LED_I_ALL			GPIO_Pin_9
#define PULSE_LED_I_1				GPIO_Pin_11
#define PULSE_LED_I_2				GPIO_Pin_10

#define PULSE_LED_I_ALL_OFF		GPIO_SetBits(GPIOB, 	PULSE_LED_I_ALL)
#define PULSE_LED_I_ALL_ON		GPIO_ResetBits(GPIOB, PULSE_LED_I_ALL)

#define PULSE_LED_I_1_OFF		GPIO_SetBits(GPIOB, 	PULSE_LED_I_1)
#define PULSE_LED_I_1_ON		GPIO_ResetBits(GPIOB, PULSE_LED_I_1)

#define PULSE_LED_I_2_OFF		GPIO_SetBits(GPIOB, 	PULSE_LED_I_2)
#define PULSE_LED_I_2_ON		GPIO_ResetBits(GPIOB, PULSE_LED_I_2)

#define PULSE_LED_II_ALL		GPIO_Pin_2
#define PULSE_LED_II_1			GPIO_Pin_3
#define PULSE_LED_II_2			GPIO_Pin_12

#define PULSE_LED_II_ALL_OFF			GPIO_SetBits(GPIOA, 	PULSE_LED_II_ALL)
#define PULSE_LED_II_ALL_ON				GPIO_ResetBits(GPIOA, PULSE_LED_II_ALL)

#define PULSE_LED_II_1_OFF			GPIO_SetBits(GPIOA, 	PULSE_LED_II_1)
#define PULSE_LED_II_1_ON				GPIO_ResetBits(GPIOA, PULSE_LED_II_1)

#define PULSE_LED_II_2_OFF			GPIO_SetBits(GPIOA, 	PULSE_LED_II_2)
#define PULSE_LED_II_2_ON				GPIO_ResetBits(GPIOA, PULSE_LED_II_2)

#endif
